### ISSUE TITLE
Versioning synchronization

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/grunt-stryker#5]
Right now grunt-stryker is v0.1.0. Is it an idea to keep the versionnumber in sync with stryker? That would make the next release of grunt-stryker v0.4.0.

**Comment by nicojs** [comment]
Well... i think this is a bad idea. Every module should have its own version management. Keeping versions in sync doesn't really make sense if you are implementing strict [semver](http://semver.org/). We could have a mension in the readme that the current version is for `stryker@^0.4.0`. If we do that, we should have an automated process to keep it in sync with the stryker `peerDependency` version.

**Comment by nicojs** [comment]
@simondel Can we close this issue?
