### ISSUE TITLE
Can't install grunt-stryker

### ISSUE THREAD

**Issue by mthmulders** [stryker-mutator/grunt-stryker#6]
My platform is Windows, Node v4.4.6, NPM v2.15.5. When I follow the [Quickstart](http://stryker-mutator.github.io/quickstart.html), NPM gives me:

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! node v4.4.6
    npm ERR! npm  v2.15.5
    npm ERR! code EPEERINVALID

    npm ERR! peerinvalid The package stryker@0.4.2 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer grunt-stryker@0.1.0 wants stryker@^0.3.1

The npm-debug.log is available upon request, I cannot post it here.

**Comment by nicojs** [comment]
I just did a new release with peerDependency `stryker@^0.4.1`. Can you please confirm that this fixes your issue?

**Comment by mthmulders** [comment]
Yep, installation succeeds. Thanks!

**Comment by nicojs** [comment]
Great! Please let us know if you have any issues.
